Update CI-runpod_dep.yml

diff --git a/.github/workflows/CI-runpod_dep.yml b/.github/workflows/CI-runpod_dep.yml
--- a/.github/workflows/CI-runpod_dep.yml
+++ b/.github/workflows/CI-runpod_dep.yml
@@ -18,6 +18,11 @@ jobs:
       - name: Check for new package version and update
         run: |
           echo "CURRENT_VERSION=$(grep -oP 'runpod==\K[^"]+' ./builder/requirements.txt)" >> $GITHUB_ENV
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/pypi/runpod/json)
+          if [ "$RESPONSE" -ne 200 ]; then
+              echo "Failed to fetch the new version, HTTP response code: $RESPONSE"
+              exit 1
+          fi
           echo "NEW_VERSION=$(curl -s https://pypi.org/pypi/runpod/json | jq -r .info.version)" >> $GITHUB_ENV
           if [ -z "$NEW_VERSION" ]; then
               echo "Failed to fetch the new version."
